epoch: 30
batch_size: 64
num_workers: 0
lr: 0.008
lr_min: 0.00001
weight_decay: 0.001

device: 'cuda:0' # cpu or cuda:0

data_path: 'data/pie'
balance: False

log_dir: 'log/pie/train_001'

observe_time: 16

kps_ch: 3
embedding_ch: 64
hidden_ch: 4

# module True or False
speed: True
center: True
area: False
seg: False
dist: True

